import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {once} from 'node:events';import {grade,processGrade,csvCell} from '../grading.js';
test('berekening en volledigheid',()=>{assert.equal(grade([1,1,1,1,1,1],1),0);assert.equal(grade([4,4,4,4,4,4],4),10);assert.equal(grade([3,3,3,3,3,3],null),null);assert.equal(grade([4,4,4,4,4,4],1),60/7);assert.equal(processGrade([{grade:4},{grade:8}],2),6);assert.equal(processGrade([{grade:4}],2),null);assert.equal(processGrade([{grade:null}],1),null);assert.equal(csvCell('=SUM(A1)'),`"'=SUM(A1)"`);});
test('opslag, autorisatie, sessies, CSV en inlogbegrenzing',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'dp-test-'));let proc;const port=3197,base=`http://localhost:${port}`;
 async function start(database=true){proc=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(port),TEACHER_PASSWORD:'test-only-secret',DATABASE_PATH:database?join(dir,'db.sqlite'):'',NODE_ENV:'development'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{proc.stdout.once('data',resolve);proc.once('exit',()=>reject(Error('Start mislukt')));});}
 async function stop(){proc.kill();await once(proc,'exit');}
 async function call(path,data,cookie,origin){const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(cookie?{cookie}:{}),...(origin?{origin}:{})},body:data?JSON.stringify(data):undefined});return {r,b:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};}
 try{await start();assert.equal((await call('teacher')).r.status,401);assert.equal((await call('teacher/export')).r.status,401);assert.equal((await call('login',{password:'test-only-secret'},null,'https://evil.test')).r.status,403);
 const login=await call('login',{password:'test-only-secret'});const teacher=login.r.headers.get('set-cookie').split(';')[0];assert.match(login.r.headers.get('set-cookie'),/HttpOnly/);assert.match(login.r.headers.get('set-cookie'),/SameSite=Strict/);
 assert.equal((await call('teacher/groups',{expedition:'Campus@Sea',name:'Nieuwe groep',names:['Piet Voorbeeld','Anna Demo','Mo Test']},teacher)).r.status,201);
 let snapshot=(await call('teacher',null,teacher)).b;const newGroup=snapshot.groups.at(-1);assert.equal((await call('teacher/groups',{id:newGroup.id,expedition:'Campus@Sea',name:'Aangepast',names:['Piet Voorbeeld','Anna Demo']},teacher)).r.status,201);const members=snapshot.students.filter(s=>s.group_id===snapshot.groups[0].id);const s=members[0];
 const sl=await call('student-login',{name:s.name,code:s.code,expedition:snapshot.groups[0].expedition});const student=sl.r.headers.get('set-cookie').split(';')[0];const own=(await call('student',null,student)).b;assert.equal(own.members.length,2);assert.equal('received' in own,false);assert.equal('code' in own.members[0],false);assert.equal((await call('teacher',null,student)).r.status,401);assert.equal((await call('teacher/export',null,student)).r.status,401);
 const reviews=members.map(m=>({target:m.id,answers:Array.from({length:6},()=>({score:4,comment:'Goed meegewerkt'}))}));assert.equal((await call('submit',{reviews:reviews.slice(1)},student)).r.status,400);assert.equal((await call('submit',{reviews},student)).r.status,201);assert.equal((await call('submit',{reviews},student)).r.status,409);assert.equal((await call('teacher/groups',{id:s.group_id,expedition:'Stad van de Toekomst',name:'Wijziging',names:['Nieuwe Naam']},teacher)).r.status,409);
 assert.equal((await call('teacher/honesty',{id:s.id,score:4},teacher)).r.status,200);snapshot=(await call('teacher',null,teacher)).b;assert.equal(snapshot.students.find(x=>x.id===s.id).received[0].grade,10);assert.equal(snapshot.students.find(x=>x.id===s.id).processGrade,null);
 const other=members[1],ol=await call('student-login',{name:other.name,code:other.code,expedition:snapshot.groups[0].expedition}),oc=ol.r.headers.get('set-cookie').split(';')[0];await call('submit',{reviews},oc);await call('teacher/honesty',{id:other.id,score:4},teacher);snapshot=(await call('teacher',null,teacher)).b;assert.equal(snapshot.students.find(x=>x.id===s.id).processGrade,10);
 const csv=await call('teacher/export',null,teacher);assert.match(csv.b,/Goed meegewerkt/);assert.match(csv.b,/10,0/);
 await stop();await start();const relog=await call('login',{password:'test-only-secret'}),tc=relog.r.headers.get('set-cookie').split(';')[0];assert.equal((await call('teacher',null,tc)).b.students.find(x=>x.id===s.id).processGrade,10);
 await call('logout',{},tc);assert.equal((await call('teacher',null,tc)).r.status,401);for(let i=0;i<4;i++)await call('login',{password:'wrong'});assert.equal((await call('login',{password:'wrong'})).r.status,429);
 await stop();await start(false);const missing=await call('status');assert.equal(missing.r.status,503);assert.match(missing.b.error,/DATABASE_PATH/);
 }finally{if(proc.exitCode===null)await stop();rmSync(dir,{recursive:true,force:true});}
});
