import {validTeacher,sameOrigin} from '@/app/teacher-auth';
import {db} from '@/db/raw';
import {members,projects} from '@/app/config';
export async function GET(req:Request){if(!await validTeacher(req))return Response.json({error:'Log in als docent.'},{status:401});try{const rows=await db().prepare("SELECT id,payload FROM records WHERE id LIKE 'submission:%' OR id LIKE 'honesty:%'").all();return Response.json({records:rows.results.map((r:any)=>({id:r.id,...JSON.parse(r.payload)}))},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Gegevens zijn tijdelijk niet beschikbaar. Probeer opnieuw.'},{status:503});}}
export async function POST(req:Request){if(!sameOrigin(req))return new Response(null,{status:403});try{const b=await req.json();if(!projects.some(p=>p.id===b.project))return Response.json({error:'Onbekende expeditie'},{status:400});
let id:string,payload:any;
if(b.kind==='honesty'){if(!await validTeacher(req))return Response.json({error:'Log in als docent.'},{status:401});if(!members(b.project,b.actor)||!Number.isInteger(b.score)||b.score<1||b.score>4)return Response.json({error:'Kies een score van 1 tot 4.'},{status:400});id=`honesty:${b.project}:${b.actor}`;payload={kind:'honesty',project:b.project,actor:b.actor,score:b.score};}
else{if(typeof b.displayName!=='string'||!b.displayName.trim()||b.displayName.length>100)return Response.json({error:'Vul je voor- en achternaam in.'},{status:400});const group=members(b.project,b.actor);if(!group||!Array.isArray(b.assessments)||b.assessments.length!==group.length)return Response.json({error:'Beoordeel jezelf en alle groepsgenoten.'},{status:400});
const targets=new Set();for(const a of b.assessments){if(!group.includes(a.target)||targets.has(a.target)||!Array.isArray(a.scores)||a.scores.length!==6||a.scores.some((s:any)=>!Number.isInteger(s)||s<1||s>4)||!Array.isArray(a.notes)||a.notes.length!==6||a.notes.some((s:any)=>typeof s!=='string'||!s.trim()||s.length>2000))return Response.json({error:'Vul alle scores en toelichtingen in.'},{status:400});targets.add(a.target);}
id=`submission:${b.project}:${b.actor}`;payload={kind:'submission',project:b.project,actor:b.actor,displayName:b.displayName.trim(),assessments:b.assessments,submittedAt:new Date().toISOString()};}
await db().prepare('INSERT INTO records(id,payload) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').bind(id,JSON.stringify(payload)).run();return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:'Opslaan is niet gelukt. Je antwoorden blijven in beeld; probeer opnieuw.'},{status:503});}}
